# $OpenBSD$

COMMENT =	authentic Microsoft Windows experience
DISTNAME =	bsod-0.1
EXTRACT_SUFX =	.tgz
CATEGORIES =	misc

HOMEPAGE =	https://www.vanheusden.com/bsod/
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# GPLv2 only
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c curses

MASTER_SITES =	https://www.vanheusden.com/bsod/

NO_TEST =	Yes

.include <bsd.port.mk>
