# $OpenBSD$

COMMENT =	another easy editor with console and X versions
DISTNAME =	aee-2.2.21
CATEGORIES =	editors x11

HOMEPAGE =	https://devio.us/~bcallah/aee/
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# Artistic
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += X11 c curses

MASTER_SITES =	https://devio.us/~bcallah/aee/

.include <bsd.port.mk>
